services:
  ecommerce-v2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:8080"
    networks:
        - ecommerce-network

  mysql-master:
    image: mysql:8.0.26
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 'pw'
      MYSQL_DATABASE: 'ecommerce'
    volumes:
      - db:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/a.sql
      - ./sql/store_procedures.sql:/docker-entrypoint-initdb.d/b.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/c.sql
    networks:
      - ecommerce-network

  mysql-slave:
    image: mysql:8.0.26
    container_name: mysql-slave
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 'pw'
      MYSQL_DATABASE: 'ecommerce'
    volumes:
      - db_slave:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/a.sql
      - ./sql/store_procedures.sql:/docker-entrypoint-initdb.d/b.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/c.sql
    networks:
      - ecommerce-network

volumes:
  db:
    driver: local
  db_slave:
    driver: local

networks:
  ecommerce-network:
    external: true